export const level3 = [
    { "code": "AFG", "name": "Afghanistan" },
    { "code": "AGO", "name": "Angola" },
    { "code": "ATG", "name": "Antigua-et-Barbuda" },
    { "code": "BEN", "name": "Bénin" },
    { "code": "BTN", "name": "Bhoutan" },
    { "code": "BFA", "name": "Burkina Faso" },
    { "code": "BDI", "name": "Burundi" },
    { "code": "CPV", "name": "Cap-Vert" },
    { "code": "COM", "name": "Comores" },
    { "code": "COD", "name": "République démocratique du Congo" },
    { "code": "COG", "name": "République du Congo" },
    { "code": "CUB", "name": "Cuba" },
    { "code": "DMA", "name": "Dominique" },
    { "code": "GNQ", "name": "Guinée équatoriale" },
    { "code": "ERI", "name": "Érythrée" },
    { "code": "SWZ", "name": "Eswatini" },
    { "code": "ETH", "name": "Éthiopie" },
    { "code": "FSM", "name": "Micronésie" },
    { "code": "GMB", "name": "Gambie" },
    { "code": "GNB", "name": "Guinée-Bissau" },
    { "code": "GRD", "name": "Grenade" },
    { "code": "HTI", "name": "Haïti" },
    { "code": "KIR", "name": "Kiribati" },
    { "code": "LCA", "name": "Sainte-Lucie" },
    { "code": "LIE", "name": "Liechtenstein" },
    { "code": "LSO", "name": "Lesotho" },
    { "code": "MWI", "name": "Malawi" },
    { "code": "MDG", "name": "Madagascar" },
    { "code": "MRT", "name": "Mauritanie" },
    { "code": "MUS", "name": "Maurice" },
    { "code": "MDA", "name": "Moldavie" },
    { "code": "MCO", "name": "Monaco" },
    { "code": "NER", "name": "Niger" },
    { "code": "PLW", "name": "Palaos" },
    { "code": "PAN", "name": "Panama" },
    { "code": "KNA", "name": "Saint-Christophe-et-Niévès" },
    { "code": "VCT", "name": "Saint-Vincent-et-les-Grenadines" },
    { "code": "WSM", "name": "Samoa" },
    { "code": "SMR", "name": "Saint-Marin" },
    { "code": "STP", "name": "Sao Tomé-et-Principe" },
    { "code": "SLE", "name": "Sierra Leone" },
    { "code": "SLB", "name": "Îles Salomon" },
    { "code": "SOM", "name": "Somalie" },
    { "code": "SSD", "name": "Soudan du Sud" },
    { "code": "TLS", "name": "Timor oriental" },
    { "code": "TON", "name": "Tonga" },
    { "code": "TUV", "name": "Tuvalu" },
    { "code": "UGA", "name": "Ouganda" },
    { "code": "ZMB", "name": "Zambie" }
]